logging:
  level:
    org:
      springframework: info

#spring:
#  security:
#    user:
#      name: taner
#      password: dummy

jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
